#################### default parameters ############################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "25px"
logo_height = "25px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "ExitTaiwan"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["posts"]
# contact form action
contact_form_action = "https://formsubmit.co/ajax/contact@exittaiwan.com" # contact form works with [https://airform.io/] or [https://formspree.io]
newsletter = "https://exittaiwan.us4.list-manage.com/subscribe/post?u=7f0798a03512327a858ddc173&amp;id=374151cb7a&amp;f_id=00855de8f0"

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "© 2025 ExitTaiwan 出台灣"
email = "contact@exittaiwan.com"

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "聯絡我們"
link = "contact"

# Page Header
[page_header]
enable = true
bg_color_lightmode = "#F4F1EB"
text_color_lightmode = "#000"
bg_color_darkmode = "#222222"
text_color_darkmode = "#fff"

# search
# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#399A4B"
include_sections = ["posts"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# announcement
# announcement module: https://github.com/gethugothemes/hugo-modules/tree/master/components/announcement
[announcement]
enable = false
expire_days = 7
content = "You must replace the **baseURL** in **hugo.toml** file when deploying, you can manage this announcement from the **params.toml** file."

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["出台灣", "ExitTaiwan", "國外自由行", "自由行", "自由行攻略", "國外旅遊", "出國旅遊", "出國自由行", "攻略"]
description = "「ExitTaiwan 出台灣」是一個為了幫助台灣人走出台灣，探索世界而誕生的生活品牌。"
author = "ExitTaiwan"
# twitter = "zeon_studio"
image = "images/og-image.jpg"


# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories","country","city", "tags" ]


# google map
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://exittaiwan.us4.list-manage.com/subscribe/post?u=7f0798a03512327a858ddc173&amp;id=374151cb7a&amp;f_id=00855de8f0"
mailchimp_form_name = "b_7f0798a03512327a858ddc173_374151cb7a"
