baseURL = '/'
languageCode = 'zh-tw'
defaultContentLanguage = "zh-tw"
hasCJKLanguage = true
enableEmoji = true
title = 'ExitTaiwan'
copyright = 'David Chen'
theme = 'hugo-theme-itheme'
paginate = 10
[params]
  email = 'contact@exittaiwan.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/floyd-li'
  [[params.about]]
    name = 'ExitTaiwan 出台灣'
    url = '/about'
  [[params.about]]
    name = '選擇目的地國家'
    url = '/tags'
  [[params.about]]
    name = '免責聲明與使用條款'
    url = '/terms'
  [[params.blogroll]]
    name = '好用資源'
    url = 'https://docs.exittaiwan.com/%E5%A5%BD%E7%94%A8%E8%B3%87%E6%BA%90'
  [[params.blogroll]]
    name = '小額贊助'
    url = 'https://ko-fi.com/exittaiwan'
  [[params.blogroll]]
    name = '內容投稿（招募中）'
    url = 'https://l.exittaiwan.com/join-waitlist'
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1