baseURL = 'https://exittaiwan.com/'
languageCode = 'zh-tw'
defaultContentLanguage = "zh-tw"
hasCJKLanguage = true
enableEmoji = true
title = 'ExitTaiwan'
copyright = 'David Chen'
theme = 'hugo-theme-itheme'
paginate = 10
[params]
  email = 'contact@exittaiwan.com'
  [[params.shop]] # 開放商城
    name = '商城'
    url = '/shop'
  [[params.hotel]]
    name = '專人服務'
    url = 'https://l.exittaiwan.com/nav-hotel'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/floyd-li'
  [[params.about]]
    name = '關於 About'
    url = '/about'
  [[params.about]]
    name = '小額贊助'
    url = 'https://exittaiwan.gumroad.com/coffee'
  [[params.about]]
    name = '免責聲明與使用條款'
    url = '/terms'
  [[params.resources]]
    name = 'Booking.com'
    url = 'https://www.booking.com/?aid=7956794'
  [[params.resources]]
    name = 'Klook'
    url = 'https://affiliate.klook.com/redirect?aid=41451&aff_adid=1007703&k_site=https%3A%2F%2Fwww.klook.com%2F'
  [[params.resources]]
    name = 'ExitTaiwan Docs'
    url = 'https://docs.exittaiwan.com'
  [[params.blogroll]]
    name = '製作旅遊手冊'
    url = 'https://exittaiwan.com/posts/%E5%A6%82%E4%BD%95%E8%A3%BD%E4%BD%9C%E6%97%85%E9%81%8A%E6%89%8B%E5%86%8A/'
  [[params.blogroll]]
    name = '自由行行李清單'
    url = 'https://exittaiwan.com/posts/%E5%87%BA%E5%9C%8B%E8%A1%8C%E6%9D%8E%E6%89%93%E5%8C%85/'
  [[params.blogroll]]
    name = '內容投稿（招募中）'
    url = 'https://app.formbricks.com/s/n8q6ubrjuooymhfxv8i684xy'
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1