[params]
  ShowCopyRight = true
  ShowMore = true
  ShowRSS = false
  docs = true
  # shop = true
  # algolia = "enable"

[assets]
  favicon = "/images/favicon.ico"
  favicon16x16 = "/images/favicon-16x16.png"
  favicon32x32 = "/images/favicon-32x32.png"
  apple_touch_icon = "/images/apple-touch-icon.png"
  safari_pinned_tab = "/images/apple-touch-icon.png"